FROM quay.io/nordstrom/java:8
MAINTAINER Store Modernization Platform Team "stmdrnztnpfrm@nordstrom.com"

USER root

RUN apt-get update -qy \
 && apt-get install -qy \
      openjdk-8-jdk

USER ubuntu
